### ISSUE TITLE
Incompatible with graphql-tag 2.0.0

### ISSUE THREAD

**Issue by abhiaiyer91** [apollographql/apollo-test-utils#17]
We changed the printer/parser exports in 2.0.0 of `graphql-tag`. The mock interfaces should use this from graphql directly

**Comment by abhiaiyer91** [comment]
@stubailo @helfer did this in https://github.com/apollographql/apollo-test-utils/pull/18

**Comment by helfer** [comment]
Thanks @abhiaiyer91 !
