### ISSUE TITLE
Problems with scalars

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-test-utils#28]
Hi. Thanks for this package. So far has been very usefull but am stuck on a following issues.
I have defined a custom scalar:

But, when I try to following, it will fail on error:

```js
const typeDefs = `
  scalar Date;
  type Query {
    helloWorld: Date
  }

  schema {
    query: Query
  }
`;

const mocks = {
  Date: () => {
    __parseValue (value) {
      return value != null ? new Date(value) : undefined;
    },
    __parseLiteral (ast) {
      return (parseInt(ast.value, 10));
    },
    __serialize(value) {
      return value instanceof Date ? value.getTime() : value;
    }
  }
  Query: () => {
    return {
      helloWorld: () => {
        return new Date();
      },
    };
  },
};
```

Error:

```
Expected a value of type \"Date\" but received: [object Object]\nGraphQL error: Expected a value of type \"Date\" but received: [object Object]"
```

Any idea what is going on? It is complaining that the Date, is not a Date.

**Comment by tomitrescak** [comment]
It gets even weirder when I implement scalar using the graphql notation:

GraphQL error: Expected a value of type \"Date\" but received: Date

```js
const typeDefs = `
  scalar Date;
  type Query {
    helloWorld: Date
  }

  schema {
    query: Query
  }
`;

const dateResolver = new GraphQLScalarType({
  name: 'Date',
  description: 'Date custom scalar type',
  parseValue(value) {
    return new Date(value); // value from the client
  },
  serialize(value) {
    return value.getTime(); // value sent to the client
  },
  parseLiteral(ast) {
    if (ast.kind === Kind.INT) {
      return parseInt(ast.value, 10); // ast value is always in string format
    }
    return null;
  }
});

const mocks = {
  Date: () => dateResolver,
  Query: () => {
    return {
      helloWorld: () => {
        return new Date();
      },
    };
  },
};

```

**Comment by tomitrescak** [comment]
Dears, any help with this would be greatly appreciated. It is blocking our testing process. for now, we manually covert all Dates to Ints, but that is no good ;(

I even found this on the Apollo mocking page, but I do not understand what you mean by "second parameter". I think you mean resolvers, but that is what I do here:

> Note: If your schema has custom scalar types, you still need to define the __serialize, __parseValue, and __parseLiteral functions, and pass them inside the second argument to makeExecutableSchema.

**Comment by tomitrescak** [comment]
OK. Solved it. The scalar resolver is not part of mocks but 'makeExecutableSchema' as per documentation. Aferwadrs it works.

**Comment by miracle2k** [comment]
I can't get this to work. No matter how I pass my custom scalars to makeExecutableSchema, I always get:  `Expected a value of type \"Date\" but received: [object Object]`.

I tried to add `preserveResolvers: true` when calling `addMockFunctionsToSchema`, but that does't make any difference.

Do you happen to have a code sample?

**Comment by miracle2k** [comment]
Got it. Needs to be such:

```
const JSONType = {
  __parseValue (value: any) {
    return value;
  },
  __parseLiteral (ast: any) {
    return ast.value;
  },
  __serialize(value: any) {
    return value;
  }
}

makeExecutableSchema({typeDefs, resolvers: {JSON: JSONType})
```

**Comment by dark06** [comment]
@tomitrescak you saved my day!
In my case, I am using `graphql-type-json` and so I only needed to pass GraphQLJSON to the resolvers

```
const GraphQLJSON = require('graphql-type-json');
const executableSchema = makeExecutableSchema({
    typeDefs: schema,
    resolvers: [resolver, {JSON: GraphQLJSON}],
});
```
