### ISSUE TITLE
Mocking mutations

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-test-utils#29]
Dears, how would you go on about mocking mutations? I want to mock store and spy on mutation calls.

**Comment by ChristianOezelt** [comment]
Create a mocked network interface, create an ApolloClient with that interface and use it in an ApolloProvider in your testcase?

If you just want to spy on when mutate is called you can also try sinon.js
Depending on what exactly you want to test.

**Comment by tomitrescak** [comment]
Thanks for your answer. For those seeking an example:

```js
const mocks = {
  Token: () => ({ // your custom resolver for 'type Token'
    expires: 1,
  }),
  Query: () => ({ // your queries
    user: () => {
      // return something
    }
  }),
  Mutation: () => ({ // your mutations
    loginWithPassword: () => {
      // return something
    }
  })
};
addMockFunctionsToSchema({ schema, mocks });
```
