### ISSUE TITLE
Any news on this?

### ISSUE THREAD

**Issue by recidive** [apollographql/apollo-test-utils#3]
Hello, is there any news on this?

Right now, is there any way I can use mockNetworkInterface in my apollo client tests?

Thanks!

**Comment by kamilkisiela** [comment]
I think it could be published after merging #4

**Comment by miltonhultgren** [comment]
Hi! Recently started using Apollo client and I'm excited for more tools to use in testing. 

Do you think someone could write a small guide about how to use this in testing for React? 

I found this article https://dev-blog.apollodata.com/seamless-integration-for-graphql-and-react-6ffc0ad3fead#.8ks60u6cm

In the testing section it gives some idea of how it could look but I couldn't get it to work by importing mockNetworkInterface from react-apollo/test-utils. (I can post a more complete example if that might help).

**Comment by helfer** [comment]
@miltonhultgren once we merge #4 (which we'll do when we have a decent enough README), you should be able to use this library 🙂  If you have some extra time, you could even figure out how to use this library yourself, and then finish the PR by writing a readme with instructions for how to use it!

**Comment by miltonhultgren** [comment]
@helfer I will try to find some time this week to do just that! Any tips for what I should include in the readme?

**Comment by helfer** [comment]
@miltonhultgren Great, thanks a lot! 🙂 I think it can be a very basic readme that just contains the following:

* The purpose of this package
* A list of the functions/classes inside, and how to use each function/class
* A complete example (eg. a test you might write for your app)

**Comment by miltonhultgren** [comment]
@helfer I've been trying in vain to find time to look into this but 0 luck, I'm in the middle of planning a wedding and moving abroad (looking for jobs) so I don't think I'll be able to help here I'm afriad. :(

**Comment by helfer** [comment]
I just published a very basic package with an even more basic readme.
