### ISSUE TITLE
Passing context to mocked queries

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-test-utils#32]
Hi, currently the third parameter of mocked query, that contains server context is always null.
Is there any way to specify server context?

```
  addMockFunctionsToSchema({
    schema,
    mocks: {
       Query: () => ({
           mockedQuery(a, b, c, d) => ({   // c is always null
           )}
       })
   }
  });
```

**Comment by xavcz** [comment]
👋 yep, it's possible!

The _fourth_ parameter of `graphql-js` used by `apollo-test-utils` defines the context and is hardcoded to `{}`.

To solve this problem, you can either make a PR to this package to allow a custom context or use `graphql-js` directly

- Implementation in `apollo-test-utils`: https://github.com/apollographql/apollo-test-utils/blob/master/src/mocks/mockNetworkInterfaceWithSchema.ts#L15
- `graphql-js` signature: https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L59-L67

**Comment by tomitrescak** [comment]
Thanks! Just did PR :)
