### ISSUE TITLE
Needs to peer depend on `graphql-tag@1.3.1` or something

### ISSUE THREAD

**Issue by tmeasday** [apollographql/apollo-test-utils#6]
I added this to a project, it didn't complain; but my version of `graphql-tag` was too old. Fun times w/ npm.

**Comment by tmeasday** [comment]
FTR the error I saw was:

```
Module not found: Error: Cannot resolve module 'graphql-tag/bundledPrinter' in /Users/tom/Chroma/tasklist-zero-client/node_modules/apollo-test-utils/dist/src/mocks
```

**Comment by helfer** [comment]
Hm, interesting! I would have assumed that having `graphql-tag: 1.3.1` in package.json would require at least 1.3.1. It doesn't? 🤔

**Comment by tmeasday** [comment]
Well I mean it's a dev dependency, but I am a simple user of the library. I guess it's not a peer so much as a direct dep.

**Comment by helfer** [comment]
Oh, you're right. I thought it was a dependency, not just a dev dependency.
